name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Update sponsors
        run: cd sponsorkit && npm install sponsorkit@0.8.7 && npx sponsorkit -o sponsors.svg
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: CollinHeist


      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update sponsors.svg"
          add: "sponsorkit/sponsors.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
